// engine.ts — a faithful model of the WebAuthn / FIDO2 ceremony using real
// ECDSA P-256 signatures via Web Crypto. This is NOT the full CBOR/COSE +
// attestation wire format; it models the SECURITY-RELEVANT logic:
//   * a credential keypair generated by the "authenticator", bound to an RP ID
//   * the private key NEVER leaves the authenticator (server stores only public)
//   * authentication = sign(challenge || rpIdHash || origin || counter)
//   * the server verifies the real signature and checks challenge/origin/counter
// The attack functions show WHY the design resists phishing, replay, and cloning.

const enc = new TextEncoder();
const ALGO = { name: 'ECDSA', namedCurve: 'P-256' } as const;
const SIGN = { name: 'ECDSA', hash: 'SHA-256' } as const;

function b64(buf: ArrayBuffer): string {
    const u = new Uint8Array(buf);
    let s = '';
    for (let i = 0; i < u.length; i++) s += String.fromCharCode(u[i]);
    return btoa(s);
}
function unb64(s: string): Uint8Array {
    const bin = atob(s);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}
export function randomChallenge(): string {
    const a = new Uint8Array(32);
    crypto.getRandomValues(a);
    return b64(a.buffer);
}
async function sha256Hex(s: string): Promise<string> {
    const d = await crypto.subtle.digest('SHA-256', enc.encode(s) as BufferSource);
    return Array.from(new Uint8Array(d)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

// =====================================================================
// The Authenticator (phone / security key). Holds private keys; the
// private key material never leaves this object in a real device.
// =====================================================================
export interface StoredCredential {
    credentialId: string;
    rpId: string; // the relying party this credential is bound to
    publicKeyJwk: JsonWebKey; // what the SERVER stores
    signCount: number; // authenticator's monotonic counter
}

interface PrivateRecord {
    credentialId: string;
    rpId: string;
    privateKey: CryptoKey;
    signCount: number;
}

export class Authenticator {
    private store = new Map<string, PrivateRecord>();

    // Registration: make a new credential keypair bound to rpId. Returns the
    // PUBLIC credential the server will store. Private key stays inside.
    async makeCredential(rpId: string): Promise<StoredCredential> {
        const kp = await crypto.subtle.generateKey(ALGO, true, ['sign', 'verify']);
        const publicKeyJwk = await crypto.subtle.exportKey('jwk', kp.publicKey);
        const credentialId = b64(crypto.getRandomValues(new Uint8Array(16)).buffer);
        this.store.set(credentialId, { credentialId, rpId, privateKey: kp.privateKey, signCount: 0 });
        return { credentialId, rpId, publicKeyJwk, signCount: 0 };
    }

    // Authentication: the authenticator signs over the client data + auth data.
    // CRITICAL: it signs the ORIGIN the browser actually saw and the rpId hash —
    // this is what defeats phishing. It will refuse if the rpId doesn't match
    // the credential (a real authenticator binds the credential to the RP).
    async getAssertion(
        credentialId: string,
        challenge: string,
        origin: string,
        rpId: string,
    ): Promise<Assertion | { error: string }> {
        const rec = this.store.get(credentialId);
        if (!rec) return { error: 'No such credential on this authenticator.' };
        if (rec.rpId !== rpId) {
            return { error: `Credential is bound to "${rec.rpId}", not "${rpId}" — authenticator refuses.` };
        }
        rec.signCount += 1;
        const rpIdHash = await sha256Hex(rpId);
        const clientData = JSON.stringify({ type: 'webauthn.get', challenge, origin });
        const clientDataHash = await sha256Hex(clientData);
        const authData = `${rpIdHash}|${rec.signCount}`;
        const signedBytes = enc.encode(authData + '|' + clientDataHash);
        const sig = await crypto.subtle.sign(SIGN, rec.privateKey, signedBytes as BufferSource);
        return {
            credentialId,
            signatureB64: b64(sig),
            authData,
            clientDataJSON: clientData,
            signCount: rec.signCount,
        };
    }

    // expose count for the clone demo
    peekCount(credentialId: string): number {
        return this.store.get(credentialId)?.signCount ?? -1;
    }
}

export interface Assertion {
    credentialId: string;
    signatureB64: string;
    authData: string; // rpIdHash|signCount
    clientDataJSON: string; // includes the origin the browser saw
    signCount: number;
}

// =====================================================================
// The Relying Party server: stores public credentials + verifies assertions.
// =====================================================================
export interface VerifyContext {
    expectedChallenge: string;
    expectedOrigin: string;
    expectedRpId: string;
}

export interface VerifyResult {
    ok: boolean;
    checks: { label: string; pass: boolean; detail: string }[];
    summary: string;
}

export class RelyingParty {
    credentials = new Map<string, StoredCredential>();
    private lastSeenCount = new Map<string, number>();

    register(cred: StoredCredential): void {
        this.credentials.set(cred.credentialId, cred);
        this.lastSeenCount.set(cred.credentialId, cred.signCount);
    }

    async verifyAssertion(a: Assertion, ctx: VerifyContext): Promise<VerifyResult> {
        const checks: VerifyResult['checks'] = [];
        const cred = this.credentials.get(a.credentialId);
        if (!cred) {
            return { ok: false, checks: [{ label: 'Known credential', pass: false, detail: 'Unknown credential ID.' }], summary: 'Rejected: unknown credential.' };
        }

        const client = JSON.parse(a.clientDataJSON) as { type: string; challenge: string; origin: string };

        // 1. challenge matches the one the server issued (anti-replay)
        const challengeOk = client.challenge === ctx.expectedChallenge;
        checks.push({ label: 'Challenge match', pass: challengeOk, detail: challengeOk ? 'Fresh challenge matches.' : 'Challenge does not match — possible replay.' });

        // 2. origin matches (anti-phishing): the browser-reported origin is signed
        const originOk = client.origin === ctx.expectedOrigin;
        checks.push({ label: 'Origin match', pass: originOk, detail: originOk ? `Origin ${client.origin} matches.` : `Origin ${client.origin} != expected ${ctx.expectedOrigin} — phishing blocked.` });

        // 3. rpId hash matches expected
        const expectedRpHash = await sha256Hex(ctx.expectedRpId);
        const rpHashOk = a.authData.startsWith(expectedRpHash + '|');
        checks.push({ label: 'RP ID hash', pass: rpHashOk, detail: rpHashOk ? 'RP ID hash matches.' : 'RP ID hash mismatch.' });

        // 4. signature verifies against the stored public key (the real crypto)
        let sigOk = false;
        try {
            const key = await crypto.subtle.importKey('jwk', cred.publicKeyJwk, ALGO, false, ['verify']);
            const clientDataHash = await sha256Hex(a.clientDataJSON);
            const signedBytes = enc.encode(a.authData + '|' + clientDataHash);
            sigOk = await crypto.subtle.verify(SIGN, key, unb64(a.signatureB64) as BufferSource, signedBytes as BufferSource);
        } catch {
            sigOk = false;
        }
        checks.push({ label: 'Signature valid', pass: sigOk, detail: sigOk ? 'ECDSA signature verifies against stored public key.' : 'Signature does not verify.' });

        // 5. signature counter strictly increasing (clone detection)
        const last = this.lastSeenCount.get(a.credentialId) ?? 0;
        const counterOk = a.signCount > last;
        checks.push({ label: 'Counter increasing', pass: counterOk, detail: counterOk ? `Counter ${a.signCount} > ${last}.` : `Counter ${a.signCount} <= ${last} — possible cloned authenticator.` });
        if (counterOk) this.lastSeenCount.set(a.credentialId, a.signCount);

        const ok = checks.every((c) => c.pass);
        const firstBad = checks.find((c) => !c.pass);
        return { ok, checks, summary: ok ? 'Authenticated — all checks passed.' : `Rejected: ${firstBad?.detail}` };
    }
}

export function shortB64(s: string, n = 16): string {
    return s.length > n ? s.slice(0, n) + '…' : s;
}
