// engine.ts — a faithful model of the WebAuthn / FIDO2 ceremony using real
// ECDSA P-256 signatures via Web Crypto. This is NOT the full CBOR/COSE +
// attestation wire format; it models the SECURITY-RELEVANT logic:
//   * a credential keypair generated by the "authenticator", bound to an RP ID
//   * the private key NEVER leaves the authenticator (server stores only public)
//   * authentication = sign(challenge || rpIdHash || flags || counter)
//   * the server verifies the real signature and checks challenge/origin/counter
// The attack functions show WHY the design resists phishing, replay, and cloning.
//
// Path B extensions (see PRODUCTION_GAPS #1 and #5 in data.ts):
//   * UP (User Present) and UV (User Verified) flag bits in authData
//   * Discoverable-credential lookup by rpId (resident-key style)
//   * VerifyContext gains optional requireUP / requireUV so the demo can show
//     what happens when an RP demands UV the authenticator did not provide.

const enc = new TextEncoder();
const ALGO = { name: 'ECDSA', namedCurve: 'P-256' } as const;
const SIGN = { name: 'ECDSA', hash: 'SHA-256' } as const;

// WebAuthn authData flag bits (subset). Real authData uses byte 32:
//   bit 0 — UP (User Present)
//   bit 2 — UV (User Verified)
//   bit 6 — AT (Attested credential data included)
//   bit 7 — ED (Extension data included)
// We model UP + UV here; AT/ED are out of scope for this teaching simulator.
export const AUTH_FLAG_UP = 0x01;
export const AUTH_FLAG_UV = 0x04;

function b64(buf: ArrayBuffer): string {
    const u = new Uint8Array(buf);
    let s = '';
    for (let i = 0; i < u.length; i++) s += String.fromCharCode(u[i]);
    return btoa(s);
}
function unb64(s: string): Uint8Array {
    const bin = atob(s);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
}
export function randomChallenge(): string {
    const a = new Uint8Array(32);
    crypto.getRandomValues(a);
    return b64(a.buffer);
}
async function sha256Hex(s: string): Promise<string> {
    const d = await crypto.subtle.digest('SHA-256', enc.encode(s) as BufferSource);
    return Array.from(new Uint8Array(d)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

// =====================================================================
// The Authenticator (phone / security key). Holds private keys; the
// private key material never leaves this object in a real device.
// =====================================================================
export interface StoredCredential {
    credentialId: string;
    rpId: string; // the relying party this credential is bound to
    publicKeyJwk: JsonWebKey; // what the SERVER stores
    signCount: number; // authenticator's monotonic counter
}

interface PrivateRecord {
    credentialId: string;
    rpId: string;
    privateKey: CryptoKey;
    signCount: number;
}

export interface AssertionOptions {
    userPresent?: boolean; // default true — authenticator was touched
    userVerified?: boolean; // default true — biometric / PIN was done
}

export class Authenticator {
    private store = new Map<string, PrivateRecord>();

    // Registration: make a new credential keypair bound to rpId. Returns the
    // PUBLIC credential the server will store. Private key stays inside.
    async makeCredential(rpId: string): Promise<StoredCredential> {
        const kp = await crypto.subtle.generateKey(ALGO, true, ['sign', 'verify']);
        const publicKeyJwk = await crypto.subtle.exportKey('jwk', kp.publicKey);
        const credentialId = b64(crypto.getRandomValues(new Uint8Array(16)).buffer);
        this.store.set(credentialId, { credentialId, rpId, privateKey: kp.privateKey, signCount: 0 });
        return { credentialId, rpId, publicKeyJwk, signCount: 0 };
    }

    // Authentication: the authenticator signs over the client data + auth data.
    // CRITICAL: it signs the ORIGIN the browser actually saw and the rpId hash —
    // this is what defeats phishing. It will refuse if the rpId doesn't match
    // the credential (a real authenticator binds the credential to the RP).
    async getAssertion(
        credentialId: string,
        challenge: string,
        origin: string,
        rpId: string,
        options: AssertionOptions = {},
    ): Promise<Assertion | { error: string }> {
        const rec = this.store.get(credentialId);
        if (!rec) return { error: 'No such credential on this authenticator.' };
        if (rec.rpId !== rpId) {
            return { error: `Credential is bound to "${rec.rpId}", not "${rpId}" — authenticator refuses.` };
        }
        return this.signWith(rec, challenge, origin, rpId, options);
    }

    // Discoverable-credential lookup. The browser asks the authenticator
    // "do you have any credentials for this rpId?" and the authenticator
    // picks one without the relying party naming it first.
    async getAssertionByRpId(
        rpId: string,
        challenge: string,
        origin: string,
        options: AssertionOptions = {},
    ): Promise<Assertion | { error: string }> {
        for (const rec of this.store.values()) {
            if (rec.rpId === rpId) {
                return this.signWith(rec, challenge, origin, rpId, options);
            }
        }
        return { error: `No discoverable credential on this authenticator for ${rpId}.` };
    }

    // List the public credential metadata bound to an rpId. Useful for the UI
    // to show "the authenticator can pick from these" without revealing keys.
    listCredentials(rpId: string): { credentialId: string; rpId: string; signCount: number }[] {
        const out: { credentialId: string; rpId: string; signCount: number }[] = [];
        for (const rec of this.store.values()) {
            if (rec.rpId === rpId) {
                out.push({ credentialId: rec.credentialId, rpId: rec.rpId, signCount: rec.signCount });
            }
        }
        return out;
    }

    private async signWith(
        rec: PrivateRecord,
        challenge: string,
        origin: string,
        rpId: string,
        options: AssertionOptions,
    ): Promise<Assertion> {
        rec.signCount += 1;
        const up = options.userPresent !== false; // default true
        const uv = options.userVerified !== false; // default true
        const flags = (up ? AUTH_FLAG_UP : 0) | (uv ? AUTH_FLAG_UV : 0);
        const rpIdHash = await sha256Hex(rpId);
        const clientData = JSON.stringify({ type: 'webauthn.get', challenge, origin });
        const clientDataHash = await sha256Hex(clientData);
        // authData format extended to include the flags byte. Real WebAuthn is
        // a packed binary; this string-pipe encoding keeps the lesson readable.
        const authData = `${rpIdHash}|${flags}|${rec.signCount}`;
        const signedBytes = enc.encode(authData + '|' + clientDataHash);
        const sig = await crypto.subtle.sign(SIGN, rec.privateKey, signedBytes as BufferSource);
        return {
            credentialId: rec.credentialId,
            signatureB64: b64(sig),
            authData,
            clientDataJSON: clientData,
            signCount: rec.signCount,
            flags,
        };
    }

    // expose count for the clone demo
    peekCount(credentialId: string): number {
        return this.store.get(credentialId)?.signCount ?? -1;
    }
}

export interface Assertion {
    credentialId: string;
    signatureB64: string;
    authData: string; // rpIdHash|flags|signCount
    clientDataJSON: string; // includes the origin the browser saw
    signCount: number;
    flags: number; // UP/UV bits the authenticator asserted
}

// =====================================================================
// The Relying Party server: stores public credentials + verifies assertions.
// =====================================================================
export interface VerifyContext {
    expectedChallenge: string;
    expectedOrigin: string;
    expectedRpId: string;
    requireUP?: boolean; // RP policy: was the user present at the device?
    requireUV?: boolean; // RP policy: did the user complete biometric/PIN?
}

export interface VerifyResult {
    ok: boolean;
    checks: { label: string; pass: boolean; detail: string }[];
    summary: string;
}

export class RelyingParty {
    credentials = new Map<string, StoredCredential>();
    private lastSeenCount = new Map<string, number>();

    register(cred: StoredCredential): void {
        this.credentials.set(cred.credentialId, cred);
        this.lastSeenCount.set(cred.credentialId, cred.signCount);
    }

    async verifyAssertion(a: Assertion, ctx: VerifyContext): Promise<VerifyResult> {
        const checks: VerifyResult['checks'] = [];
        const cred = this.credentials.get(a.credentialId);
        if (!cred) {
            return { ok: false, checks: [{ label: 'Known credential', pass: false, detail: 'Unknown credential ID.' }], summary: 'Rejected: unknown credential.' };
        }

        const client = JSON.parse(a.clientDataJSON) as { type: string; challenge: string; origin: string };

        // 1. challenge matches the one the server issued (anti-replay)
        const challengeOk = client.challenge === ctx.expectedChallenge;
        checks.push({ label: 'Challenge match', pass: challengeOk, detail: challengeOk ? 'Fresh challenge matches.' : 'Challenge does not match — possible replay.' });

        // 2. origin matches (anti-phishing): the browser-reported origin is signed
        const originOk = client.origin === ctx.expectedOrigin;
        checks.push({ label: 'Origin match', pass: originOk, detail: originOk ? `Origin ${client.origin} matches.` : `Origin ${client.origin} != expected ${ctx.expectedOrigin} — phishing blocked.` });

        // 3. rpId hash matches expected
        const expectedRpHash = await sha256Hex(ctx.expectedRpId);
        const rpHashOk = a.authData.startsWith(expectedRpHash + '|');
        checks.push({ label: 'RP ID hash', pass: rpHashOk, detail: rpHashOk ? 'RP ID hash matches.' : 'RP ID hash mismatch.' });

        // 4. signature verifies against the stored public key (the real crypto)
        let sigOk = false;
        try {
            const key = await crypto.subtle.importKey('jwk', cred.publicKeyJwk, ALGO, false, ['verify']);
            const clientDataHash = await sha256Hex(a.clientDataJSON);
            const signedBytes = enc.encode(a.authData + '|' + clientDataHash);
            sigOk = await crypto.subtle.verify(SIGN, key, unb64(a.signatureB64) as BufferSource, signedBytes as BufferSource);
        } catch {
            sigOk = false;
        }
        checks.push({ label: 'Signature valid', pass: sigOk, detail: sigOk ? 'ECDSA signature verifies against stored public key.' : 'Signature does not verify.' });

        // 5. signature counter strictly increasing (clone detection)
        const last = this.lastSeenCount.get(a.credentialId) ?? 0;
        const counterOk = a.signCount > last;
        checks.push({ label: 'Counter increasing', pass: counterOk, detail: counterOk ? `Counter ${a.signCount} > ${last}.` : `Counter ${a.signCount} <= ${last} — possible cloned authenticator.` });
        if (counterOk) this.lastSeenCount.set(a.credentialId, a.signCount);

        // 6 (optional). User Present — RP policy
        if (ctx.requireUP) {
            const upOk = (a.flags & AUTH_FLAG_UP) !== 0;
            checks.push({ label: 'User present (UP)', pass: upOk, detail: upOk ? 'Authenticator confirms user was present (UP flag set).' : 'UP flag NOT set — RP requires the user to actually touch the authenticator.' });
        }

        // 7 (optional). User Verified — RP policy
        if (ctx.requireUV) {
            const uvOk = (a.flags & AUTH_FLAG_UV) !== 0;
            checks.push({ label: 'User verified (UV)', pass: uvOk, detail: uvOk ? 'Authenticator performed biometric / PIN verification (UV flag set).' : 'UV flag NOT set — RP requires user verification (biometric or PIN).' });
        }

        const ok = checks.every((c) => c.pass);
        const firstBad = checks.find((c) => !c.pass);
        return { ok, checks, summary: ok ? 'Authenticated — all checks passed.' : `Rejected: ${firstBad?.detail}` };
    }
}

export function shortB64(s: string, n = 16): string {
    return s.length > n ? s.slice(0, n) + '…' : s;
}
